// ============================================================
// scripts/seedAll.js
// Run: node scripts/seedAll.js  (from /backend)
// Seeds: Studios + Productions + Jobs into MongoDB Atlas
// ============================================================
import mongoose   from 'mongoose';
import dotenv     from 'dotenv';
import Studio     from '../models/Studio.js';
import Production from '../models/Production.js';
import Job        from '../models/Job.js';
dotenv.config();

// ── STUDIOS ──────────────────────────────────────────────────────
const studios = [
  { name:'Tyler Perry Studios',slug:'tyler-perry-studios',image:'https://s3-media0.fl.yelpcdn.com/bphoto/Ith4hrenY_11O704hfRg7A/o.jpg',description:'330-acre studio complex built on former Fort McPherson. The largest studio lot in the US, featuring 12 purpose-built soundstages.',address:'315 Deshler St SW, Atlanta, GA 30310',location:{type:'Point',coordinates:[-84.4340,33.7134]},founded:2019,acres:330,stages:12,owner:'Tyler Perry',type:'Major',website:'https://www.tylerperrystudios.com',notableShows:['Sistas','The Oval','Zatima','Bruh'],notableFilms:['Acrimony','A Madea Family Funeral'] },
  { name:'Trilith Studios',slug:'trilith-studios',description:'Formerly Pinewood Atlanta. Home to Marvel\'s Avengers franchise. 700 acres, 23 stages — one of the largest purpose-built studio complexes worldwide.',address:'461 Sandy Creek Rd, Fayetteville, GA 30214',location:{type:'Point',coordinates:[-84.4609,33.4479]},founded:2014,acres:700,stages:23,type:'Major',website:'https://www.trilith.com',notableFilms:['Black Panther','Avengers: Endgame','Ant-Man','Spider-Man: Homecoming','Baby Driver'],notableShows:['Cobra Kai','Doom Patrol','Loki'] },
  { name:'Assembly Studios Atlanta',slug:'assembly-studios-atlanta',description:'State-of-the-art 135-acre studio campus in Doraville. Opened 2021, built on former GM plant site with 8 stages and cutting-edge production infrastructure.',address:'3400 Doraville Rd, Doraville, GA 30340',location:{type:'Point',coordinates:[-84.2697,33.8987]},founded:2021,acres:135,stages:8,type:'Major',website:'https://www.assemblystudios.com',notableFilms:['Black Panther: Wakanda Forever'],notableShows:['The Walking Dead: Dead City'] },
  { name:'EUE/Screen Gems Studios Atlanta',slug:'eue-screen-gems-atlanta',description:'One of Atlanta\'s original major studios. 32 acres, 10 stages. Home to Stranger Things, Ozark, and Mindhunter.',address:'1 Filmworks Way NW, Atlanta, GA 30318',location:{type:'Point',coordinates:[-84.4350,33.7750]},founded:2010,acres:32,stages:10,type:'Major',website:'https://www.euescreengemsstudios.com',notableFilms:['Guardians of the Galaxy Vol. 3','Creed III'],notableShows:['Stranger Things','Mindhunter','Ozark'] },
  { name:'Atlanta Metro Studios',slug:'atlanta-metro-studios',description:'Mid-size independent studio on the westside. 12 acres, 4 stages. Popular with TV movies, commercials, and streaming originals.',address:'1365 English St NW, Atlanta, GA 30318',location:{type:'Point',coordinates:[-84.4311,33.7744]},founded:2012,acres:12,stages:4,type:'Independent',notableFilms:['Various Hallmark & BET productions'] },
  { name:'Third Rail Studios',slug:'third-rail-studios',description:'Independent boutique studio in Avondale Estates. 3 flexible stages, popular with indie productions, music videos, and streaming originals.',address:'Avondale Estates, GA 30002',location:{type:'Point',coordinates:[-84.2668,33.7743]},founded:2018,acres:8,stages:3,type:'Independent' },
];

// ── PRODUCTIONS ──────────────────────────────────────────────────
const productions = [
  { title:'Ozark',tmdbId:69050,type:'TV Series',genre:['Crime','Drama','Thriller'],years:'2017–2022',network:'Netflix',director:'Jason Bateman',cast:['Jason Bateman','Laura Linney','Julia Garner','Tom Pelphrey'],overview:'A financial advisor drags his family from Chicago to the Missouri Ozarks, where he launders money for a drug cartel. Filmed at Georgia lakes doubling for Missouri.',studio:'EUE/Screen Gems Studios Atlanta',filmingLocations:['Lake Allatoona','Gainesville GA','Lake Chatuge','EUE Screen Gems'],featured:true,independent:false,awards:[{type:'Emmy',year:2022,category:'Outstanding Drama Series',status:'Nominated'},{type:'Emmy',year:2020,category:'Outstanding Supporting Actress',status:'Won',recipient:'Julia Garner'},{type:'Emmy',year:2021,category:'Outstanding Supporting Actress',status:'Won',recipient:'Julia Garner'},{type:'Emmy',year:2022,category:'Outstanding Supporting Actress',status:'Won',recipient:'Julia Garner'}] },
  { title:'Atlanta',tmdbId:62235,type:'TV Series',genre:['Comedy','Drama'],years:'2016–2022',network:'FX/Hulu',director:'Donald Glover, Hiro Murai',cast:['Donald Glover','Brian Tyree Henry','Lakeith Stanfield','Zazie Beetz'],overview:'Two cousins navigate the Atlanta rap scene. Shot entirely in ATL neighborhoods — the most authentic portrait of the city ever filmed.',studio:'EUE/Screen Gems + on-location',filmingLocations:['Edgewood Ave','Old Fourth Ward','Vine City','Morehouse College'],featured:true,independent:true,awards:[{type:'Emmy',year:2017,category:'Outstanding Comedy Series',status:'Won'},{type:'Emmy',year:2017,category:'Outstanding Directing – Comedy',status:'Won',recipient:'Donald Glover'},{type:'Emmy',year:2017,category:'Outstanding Writing – Comedy',status:'Won',recipient:'Donald Glover'},{type:'Emmy',year:2022,category:'Outstanding Comedy Series',status:'Won'},{type:'Emmy',year:2022,category:'Outstanding Lead Actor Comedy',status:'Won',recipient:'Donald Glover'},{type:'Golden Globe',year:2017,category:'Best TV Series – Musical or Comedy',status:'Won'}] },
  { title:'Stranger Things',tmdbId:66732,type:'TV Series',genre:['Sci-Fi','Horror','Drama'],years:'2016–2025',network:'Netflix',director:'The Duffer Brothers',cast:['Millie Bobby Brown','Finn Wolfhard','Winona Ryder','David Harbour'],overview:'Set in fictional Hawkins Indiana but filmed almost entirely in and around Atlanta. Most-watched show in Netflix history.',studio:'EUE/Screen Gems Studios Atlanta',filmingLocations:['Jackson GA','Douglasville GA','EUE Screen Gems','Gwinnett County'],featured:true,independent:false,awards:[{type:'Emmy',year:2022,category:'Outstanding Drama Series',status:'Nominated'},{type:'Emmy',year:2022,category:'Outstanding Supporting Actress',status:'Nominated',recipient:'Sadie Sink'},{type:'SAG',year:2022,category:'Outstanding Drama Ensemble',status:'Nominated'}] },
  { title:'Lovecraft Country',tmdbId:82816,type:'TV Series',genre:['Horror','Drama','Sci-Fi'],years:'2020',network:'HBO',director:'Misha Green',cast:['Jonathan Majors','Jurnee Smollett','Michael Kenneth Williams'],overview:'A young Black man in 1950s America navigates a racist country while facing Lovecraftian supernatural threats.',studio:'Tyler Perry Studios',filmingLocations:['Tyler Perry Studios','Various ATL locations'],featured:false,independent:false,awards:[{type:'Emmy',year:2021,category:'Outstanding Drama Series',status:'Nominated'},{type:'Emmy',year:2021,category:'Outstanding Lead Actress Drama',status:'Nominated',recipient:'Jurnee Smollett'},{type:'Emmy',year:2021,category:'Outstanding Supporting Actor',status:'Nominated',recipient:'Michael K. Williams'}] },
  { title:'Cobra Kai',tmdbId:77169,type:'TV Series',genre:['Drama','Action'],years:'2018–2024',network:'Netflix',cast:['Ralph Macchio','William Zabka','Xolo Maridueña'],overview:'Karate Kid sequel series set in the Valley but filmed entirely in Atlanta suburbs. One of Netflix\'s most-watched series globally.',studio:'Trilith Studios',filmingLocations:['Trilith Studios','Alpharetta GA','Johns Creek GA'],featured:false,independent:false,awards:[{type:'Emmy',year:2022,category:'Outstanding Comedy Series',status:'Nominated'}] },
  { title:'Mindhunter',tmdbId:67744,type:'TV Series',genre:['Crime','Drama','Thriller'],years:'2017–2019',network:'Netflix',director:'David Fincher',cast:['Jonathan Groff','Holt McCallany','Anna Torv'],overview:'FBI agents in the late 1970s interview serial killers. David Fincher\'s dark procedural shot extensively at EUE/Screen Gems.',studio:'EUE/Screen Gems Studios Atlanta',filmingLocations:['EUE Screen Gems','Various ATL suburbs'],featured:false,independent:false,awards:[{type:'Emmy',year:2018,category:'Outstanding Directing Drama',status:'Nominated',recipient:'David Fincher'}] },
  { title:'Black Panther',tmdbId:284054,type:'Film',genre:['Action','Sci-Fi','Drama'],years:'2018',director:'Ryan Coogler',cast:['Chadwick Boseman','Michael B. Jordan','Lupita Nyong\'o','Danai Gurira'],overview:'First superhero film nominated for Best Picture. Shot primarily at then-Pinewood Atlanta (now Trilith).',studio:'Trilith Studios',filmingLocations:['Trilith Studios','Biltmore Hotel Atlanta','Savannah GA'],featured:true,independent:false,awards:[{type:'Oscar',year:2019,category:'Best Picture',status:'Nominated'},{type:'Oscar',year:2019,category:'Best Costume Design',status:'Won',recipient:'Ruth E. Carter'},{type:'Oscar',year:2019,category:'Best Original Score',status:'Won',recipient:'Ludwig Göransson'},{type:'Oscar',year:2019,category:'Best Production Design',status:'Won'}] },
  { title:'Judas and the Black Messiah',tmdbId:604822,type:'Film',genre:['Drama','History','Thriller'],years:'2021',director:'Shaka King',cast:['Daniel Kaluuya','Lakeith Stanfield','Jesse Plemons'],overview:'Story of FBI informant who infiltrated the Black Panther Party. ATL-born Lakeith Stanfield stars.',studio:'Various ATL locations',filmingLocations:['Atlanta','Various Georgia locations'],featured:true,independent:false,awards:[{type:'Oscar',year:2021,category:'Best Picture',status:'Nominated'},{type:'Oscar',year:2021,category:'Best Supporting Actor',status:'Won',recipient:'Daniel Kaluuya'},{type:'Oscar',year:2021,category:'Best Original Song',status:'Won'}] },
  { title:'Baby Driver',tmdbId:339403,type:'Film',genre:['Action','Crime','Thriller'],years:'2017',director:'Edgar Wright',cast:['Ansel Elgort','Kevin Spacey','Jamie Foxx','Jon Hamm'],overview:'A music-loving getaway driver set and shot entirely in Atlanta over 60+ days on the actual streets.',studio:'Atlanta on-location',filmingLocations:['Downtown Atlanta','Underground Atlanta','Ponce City Market','I-20 Corridor'],featured:true,independent:false,awards:[{type:'Oscar',year:2018,category:'Best Film Editing',status:'Nominated'},{type:'Oscar',year:2018,category:'Best Sound Editing',status:'Nominated'},{type:'Oscar',year:2018,category:'Best Sound Mixing',status:'Nominated'}] },
  { title:'Hidden Figures',tmdbId:381284,type:'Film',genre:['Drama','History','Biography'],years:'2016',director:'Theodore Melfi',cast:['Taraji P. Henson','Octavia Spencer','Janelle Monáe','Kevin Costner'],overview:'The untold story of Black female NASA mathematicians. Shot in Atlanta with Georgia connections throughout.',studio:'Atlanta area locations',filmingLocations:['Atlanta','Marietta GA'],featured:false,independent:false,awards:[{type:'Oscar',year:2017,category:'Best Picture',status:'Nominated'},{type:'Oscar',year:2017,category:'Best Adapted Screenplay',status:'Nominated'},{type:'Oscar',year:2017,category:'Best Supporting Actress',status:'Nominated',recipient:'Octavia Spencer'}] },
  { title:'Prisoners',tmdbId:72976,type:'Film',genre:['Mystery','Drama','Thriller'],years:'2013',director:'Denis Villeneuve',cast:['Hugh Jackman','Jake Gyllenhaal','Viola Davis','Paul Dano'],overview:'Thriller about missing girls and a desperate father. Set in Pennsylvania, filmed in Newton County Georgia.',studio:'Newton County on-location',filmingLocations:['Conyers GA','Newton County GA','Loganville GA'],featured:false,independent:false,awards:[{type:'Oscar',year:2014,category:'Best Cinematography',status:'Nominated',recipient:'Roger Deakins'}] },
  { title:'Selma',tmdbId:277558,type:'Film',genre:['Drama','History','Biography'],years:'2014',director:'Ava DuVernay',cast:['David Oyelowo','Tom Wilkinson','Oprah Winfrey'],overview:'MLK Jr.\'s 1965 voting rights campaign. Ava DuVernay\'s landmark independent film with deep Atlanta roots.',studio:'Alabama + Georgia on-location',filmingLocations:['Selma AL','Atlanta locations'],featured:false,independent:true,awards:[{type:'Oscar',year:2015,category:'Best Picture',status:'Nominated'},{type:'Oscar',year:2015,category:'Best Original Song – Glory',status:'Won'}] },
];

// ── JOBS ─────────────────────────────────────────────────────────
const expires = new Date(Date.now() + 60 * 24 * 60 * 60 * 1000);
const jobs = [
  { title:'Background Extras — Period Drama Feature',company:'Casting Atlanta',description:'Seeking men and women ages 18–65 to portray 1970s Atlanta residents for upcoming Netflix feature. No experience necessary. Various shooting days through spring.',category:'Open Call',type:'Day-Player',payType:'Paid',payRange:'$148/8hr day (SAG Background Rate)',union:false,location:'Atlanta, GA',shootDates:'March–May 2025',production:'Untitled Netflix Period Drama',requirements:['Valid photo ID','Must be 18+','Reliable transportation','Availability for multiple days preferred'],applyEmail:'background@castingatl.com',status:'Active',featured:true,expiresAt:expires },
  { title:'Production Assistant (PA)',company:'Trilith Studios',description:'Entry-level PA positions for upcoming major studio feature at Trilith. Great opportunity to break into the industry working across departments.',category:'Crew',type:'Contract',payType:'Paid',payRange:'$200–$250/day',union:false,location:'Fayetteville, GA (Trilith Studios)',shootDates:'April–August 2025',requirements:['Film school or relevant experience','Driver\'s license required','Full production schedule availability','Strong organizational skills'],responsibilities:['Transport cast and crew','Assist department heads','Manage paperwork and releases','Support set operations'],applyUrl:'https://www.trilith.com/careers',status:'Active',featured:true,expiresAt:expires },
  { title:'Lead Actress — Independent Feature "Sweet Auburn"',company:'Peach State Films',description:'Seeking Black actress ages 28–40 for lead role in independent drama set in Atlanta\'s Sweet Auburn neighborhood. Character-driven story about gentrification.',category:'Acting',type:'Contract',payType:'Paid',payRange:'SAG Low Budget Scale + 10%',union:true,location:'Atlanta, GA',shootDates:'June–July 2025',production:'Sweet Auburn',genre:['Drama','Independent'],requirements:['SAG-AFTRA member preferred','Strong dramatic range','Atlanta-based preferred','Submit headshot, resume, and reel'],contactName:'Maya Johnson, Casting Director',applyEmail:'casting@peachstatefilms.com',status:'Active',featured:true,expiresAt:expires },
  { title:'Screenwriter — ATL Crime Series',company:'Pinewood Creative Group',description:'Seeking experienced TV writers for an Atlanta-set crime series in development for streaming. Must have at least one produced credit.',category:'Writing',type:'Freelance',payType:'Paid',payRange:'WGA Scale ($4,500–$8,000/episode)',union:true,location:'Atlanta, GA',remote:true,requirements:['1+ produced writing credit','Deep knowledge of Atlanta culture','WGA member or eligible'],applyEmail:'writers@pinewoodcreative.com',status:'Active',featured:false,expiresAt:expires },
  { title:'VFX Compositor',company:'Assembly Studios Atlanta',description:'Experienced VFX Compositor for full-time in-house role. Work on streaming originals and major studio features at Assembly Studios post-production.',category:'Post-Production',type:'Full-Time',payType:'Paid',payRange:'$75,000–$110,000/year',union:false,location:'Doraville, GA',requirements:['3+ years VFX compositing','Nuke proficiency required','Feature or episodic credits preferred'],responsibilities:['Composite VFX shots','Collaborate with VFX supervisor','Meet episodic delivery schedules'],applyUrl:'https://www.assemblystudios.com/careers',status:'Active',featured:false,expiresAt:expires },
  { title:'Production Intern — Tyler Perry Studios',company:'Tyler Perry Studios',description:'Paid 12-week internship rotating through multiple departments. For current students or recent graduates in film/media programs.',category:'Internship',type:'Seasonal',payType:'Paid',payRange:'$15/hour',union:false,location:'Atlanta, GA',requirements:['Enrolled in or completed film/media program','GPA 3.0+','Atlanta-based or willing to relocate'],applyUrl:'https://www.tylerperrystudios.com/internships',status:'Active',featured:false,expiresAt:expires },
  { title:'IATSE Grips & Electrics Open Call',company:'IATSE Local 479',description:'IATSE Local 479 seeking qualified Grips and Electrics for upcoming union productions in Georgia. Steady work through Q3 2025.',category:'Union',type:'Freelance',payType:'Paid',payRange:'IATSE Scale ($42–$55/hour)',union:true,location:'Various ATL productions',requirements:['IATSE Local 479 membership or application','2+ years G/E experience','Own basic kit preferred'],applyUrl:'https://www.iatselocal479.org',status:'Active',featured:false,expiresAt:expires },
  { title:'Children Casting Call — Ages 8-14',company:'Rivers Casting',description:'Open call for children ages 8–14 for supporting roles in upcoming family series filming in Decatur and Marietta. Parents must accompany.',category:'Open Call',type:'Day-Player',payType:'Paid',payRange:'$148/day + guardian fee',union:false,location:'Decatur, GA',shootDates:'May–June 2025',requirements:['Ages 8–14','Parent/guardian required','Georgia work permit (provided)','Photos submitted in advance'],applyEmail:'kids@riverscasting.com',status:'Active',featured:false,expiresAt:expires },
];

// ── RUN SEED ─────────────────────────────────────────────────────
const seed = async () => {
  await mongoose.connect(process.env.MONGO_URI);
  console.log('\n🔌  Connected to MongoDB Atlas');

  await Studio.deleteMany({});
  const seededStudios = await Studio.insertMany(studios);
  console.log(`✅  Seeded ${seededStudios.length} ATL studios`);

  // Link productions to studio ObjectIds by name match
  const enriched = productions.map(p => {
    const match = seededStudios.find(s => s.name === p.studio || s.name.includes(p.studio?.split(' ')[0]));
    return { ...p, studioId: match?._id };
  });
  await Production.deleteMany({});
  const seededProds = await Production.insertMany(enriched);
  console.log(`✅  Seeded ${seededProds.length} Emmy/Oscar ATL productions`);

  // Link jobs to studios by name
  const enrichedJobs = jobs.map(j => {
    const match = seededStudios.find(s => s.name === j.company);
    return { ...j, studioId: match?._id };
  });
  await Job.deleteMany({});
  const seededJobs = await Job.insertMany(enrichedJobs);
  console.log(`✅  Seeded ${seededJobs.length} job listings`);

  console.log('\n🎬  CineTrack ATL seed complete!\n');
  await mongoose.disconnect();
};

seed().catch(err => { console.error('❌ Seed failed:', err); process.exit(1); });

